### ISSUE TITLE
Implement the HttpManagementProxy

### ISSUE THREAD

**Issue by Miles-Garnsey** [thelastpickle/cassandra-reaper#1326]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=34017561)

To provide a new non-JMX based management mechanism, we are creating an HttpCassandraManagementProxy which implements ICassandraManagementProxy.

This class will use the client for management API which is being created [here](https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/323). It will then implement the `ICassandraManagementProxy` from [here](https://github.com/thelastpickle/cassandra-reaper/pull/1321).

## Tasks
- [x] #1340
- [x] #1341
- [x] #1342
- [x] #1343
- [x] #1344
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1325
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1347
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1353
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1357
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1361
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1375
- [x] #1377 
- [x] #1378 
- [x] #1379 
- [x] #1380 
- [x] #1381 
- [x] #1384 
- [x] #1385 
- [x] #1387 
- [x] #1388 
- [x] https://github.com/thelastpickle/cassandra-reaper/issues/1382
- [x] #1389 
- [x] #1390 
- [x] #1392

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
